name: LaTeX PDF Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install LaTeX packages
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra texlive-fonts-extra latexmk

      - name: Set up Python and install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run icpc.py script
        run: |
          python3 icpc.py

      - name: Upload algorithms.pdf
        uses: actions/upload-artifact@v3
        with:
          name: Algorithms PDF
          path: algorithms.pdf
